name: Protect Main Branch
on: [push]

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Block push to main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Direct pushes to main are not allowed. Please use a pull request."
          exit 1
